project_id = "hmjbbdwzwiqihqhjtspd"

[functions.create-user]
verify_jwt = false

[functions.send-task-notification]
verify_jwt = false

[functions.send-comment-notification]
verify_jwt = false

[functions.send-project-message-notification]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.delete-task]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.create-personal-schedule]
verify_jwt = false

[functions.create-meeting-minute]
verify_jwt = false

[functions.send-meeting-minute-notification]
verify_jwt = false
